import React,{useEffect,useState} from "react";
import {createRoot} from "react-dom/client";
import "./styles.css";

const isLocalDev = typeof window !== "undefined" && /localhost|127\.0\.0\.1/i.test(window.location.hostname);
const API = import.meta.env.VITE_API_URL || (isLocalDev ? "http://localhost:5000/api" : `${window.location.origin}/api`);
const empty={village:"",date:"",startTime:"",endTime:"",location:"",landmark:"",youthName:"",contact:""};

function App(){
 const [events,setEvents]=useState([]),[form,setForm]=useState(empty),[search,setSearch]=useState(""),[msg,setMsg]=useState(""),[formMsg,setFormMsg]=useState(""),[loading,setLoading]=useState(true);
 async function load(){try{let r=await fetch(API+"/events");setEvents(await r.json())}catch{setMsg("Backend is not connected yet.")}finally{setLoading(false)}}
 useEffect(()=>{load()},[]);
 const change=e=>setForm({...form,[e.target.name]:e.target.value});
 async function submit(e){e.preventDefault();setMsg("");setFormMsg("");const end=new Date(`${form.date}T${form.endTime}`);if(Number.isNaN(end.getTime())||end<=new Date()){setFormMsg("Please choose a future date and end time.");return}try{let r=await fetch(API+"/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});let d=await r.json();if(!r.ok)throw Error(d.message);setFormMsg("");setMsg("🎉 Annadanam added successfully!");setForm(empty);load();document.getElementById("events").scrollIntoView({behavior:"smooth"})}catch(x){setFormMsg(x.message||"Could not add event.")}}
 const list=events.filter(x=>[x.village,x.location,x.landmark,x.youthName].join(" ").toLowerCase().includes(search.toLowerCase()));
 const date=x=>new Date(x+"T00:00").toLocaleDateString("en-IN",{day:"2-digit",month:"short",year:"numeric"});
 return <><header><div className="brand"><span className="logo">🛕</span><div><b>Thorrur <i>Annadanam</i></b><small>Share food • Spread happiness</small></div></div><nav><a href="#events">Events</a><a href="#add">Add Event</a></nav></header>
 <main>
 <section className="hero"><div className="copy"><div className="tag">🙏 VINAYAKA CHAVITHI • THORRUR</div><h1>Annadanam<br/><span>for everyone.</span></h1><p>Find and share Vinayaka Chavithi Annadanam events happening in Thorrur and nearby villages.</p><div className="buttons"><a className="btn orange" href="#events">🔎 View Events</a><a className="btn green" href="#add">＋ Add Annadanam</a></div><div className="mini"><span>❤️ Community</span><span>🌿 Seva</span><span>🪔 Tradition</span></div></div><div className="art"><div className="sun"></div><img src="/vinayaka.svg" alt="Lord Ganesha"/><div className="quote">“Annadanam<br/>is the greatest seva.”</div></div></section>
 <section id="events" className="events"><div className="heading"><div><label>UPCOMING EVENTS</label><h2>Annadanam near Thorrur</h2></div><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="🔎 Search village..." /></div>{msg&&<div className="message">{msg}</div>}{loading?<div className="empty">Loading events...</div>:list.length===0?<div className="empty">No upcoming Annadanam events found.</div>:<div className="cards">{list.map(x=><article className="card" key={x._id}><div className="datebox"><b>{new Date(x.date+"T00:00").getDate()}</b><span>{new Date(x.date+"T00:00").toLocaleDateString("en-IN",{month:"short"}).toUpperCase()}</span></div><div className="cardbody"><span className="up">● UPCOMING</span><h3>{x.village}</h3><p>⏰ {x.startTime} – {x.endTime}</p><p>📍 {x.location}</p>{x.landmark&&<p>🧭 {x.landmark}</p>}{x.youthName&&<p>👤 Youth: {x.youthName}</p>}{x.contact&&<a href={"tel:"+x.contact} className="contact">📞 Contact</a>}<small>{date(x.date)}</small></div></article>)}</div>}</section>
 <section id="add" className="add"><div className="intro"><label>SHARE WITH THE COMMUNITY</label><h2>Add an Annadanam event</h2><p>No login. No registration. Enter the details and share your village event with everyone.</p><div className="flower">🌺 🪔 🌺</div></div><form onSubmit={submit}><div className="row"><label>Village Name *<input name="village" value={form.village} onChange={change} required/></label><label>Date *<input type="date" name="date" value={form.date} onChange={change} required/></label></div><div className="row"><label>Start Time *<input type="time" name="startTime" value={form.startTime} onChange={change} required/></label><label>End Time *<input type="time" name="endTime" value={form.endTime} onChange={change} required/></label></div><label>Location *<input name="location" value={form.location} onChange={change} placeholder="Temple, community hall, etc." required/></label><label>Landmark <input name="landmark" value={form.landmark} onChange={change} placeholder="Nearby landmark"/></label><label>Youth name <input name="youthName" value={form.youthName} onChange={change} placeholder="Name of the youth organizer"/></label><label>Contact number <small>(optional)</small><input name="contact" value={form.contact} onChange={change} placeholder="For event information"/></label>{formMsg&&<p className="form-message">{formMsg}</p>}<button className="submit">🛕 Publish Annadanam</button></form></section>
 </main><footer><div><b>🛕 Thorrur <i>Annadanam</i></b><span>Made with ❤️ for our community</span></div><p>Ganapati Bappa Morya • Annadanam Paramo Dharmah</p></footer></>
}
createRoot(document.getElementById("root")).render(<App/>);